aste/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # ex: /aste/
    url(r'^$', views.IndiceView.as_view(), name='indice'),
    # ex: /aste/5/
    url(r'^(?P<asta_id>[0-9]+)/$', views.dettagli, name='dettagli'),
    # ex: /aste/sendmail
    url(r'^sendmail/$', views.send_mail, name='send_mail'),
    # ex: /aste/creaAsta
    url(r'^crea/$', views.creaAsta, name='creaAsta'),

]

progetto_A/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from . import views

urlpatterns = [
    # ex: /
    url(r'^$', views.main_page, name='main_page'),
    # ex: /admin
    url(r'^admin/', admin.site.urls),
    # ex: /aste
    url(r'^aste/', include(('aste.urls', 'aste'), namespace='aste')),
    # ex: /signup
    url(r'^signup/$', views.signup, name='signup'),
    # ex: /logout
    url(r'^logout/$', views.logout_view, name='logout_view'),
    # ex: /login, /logout...
    url(r'^', include('django.contrib.auth.urls')),
    # ex: /storico
    url(r'^storico/$', views.storico_utente, name='storico'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aste/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db import models
# Create your models here.

# setto l'email dell'utente obbligatoria
User._meta.get_field('email').blank = False

class Asta(models.Model):
    descrizione = models.CharField(max_length=200, help_text='Obbligatorio.')
    data_inizio = models.DateTimeField('data e ora di inizio', help_text='Obbligatorio.')
    foto = models.ImageField(default='default.png', help_text='Obbligatorio.')
    prezzo = models.FloatField(help_text='Obbligatorio.', validators=[MinValueValidator(0.1)])
    added_by = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    class Meta:
        permissions = ( ('can_bid', 'Can Bid Auctions'), )
    def __str__(self):
        return self.descrizione
    def getState(self):
        if self.getClosingTime() < timezone.now():
            # l'asta è già finita
            return 0;
        elif self.data_inizio > timezone.now():
            # l'asta deve ancora iniziare
            return 2;
        else:
            # l'asta si sta svolgendo ora
            return 1;
    def getClosingTime(self):
        # durata dell'asta espressa in secondi
        DURATA_ASTA = 120
        return self.data_inizio + datetime.timedelta(0,DURATA_ASTA)

class Puntata(models.Model):
    asta = models.ForeignKey(
        Asta,
        on_delete=models.CASCADE,
    )
    utente = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    somma = models.FloatField()
    data_puntata = models.DateTimeField('data e ora puntata')
    class Meta: #inner class Meta
        unique_together = ('asta', 'somma')
    def __str__(self):
            return str(self.somma) + " " + str(self.data_puntata)

aste/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponseServerError
from django.views import generic
from django.utils import timezone
from django.template import loader
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q, Max, Min
from django.core.mail import EmailMessage
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from .models import Asta, Puntata

# Create your views here.

class IndiceView(generic.ListView):
    template_name = 'aste/indice.html'
    context_object_name = 'latest_auctions_list'
    paginate_by = 5

    def get_queryset(self):
        # seleziona solo gli elementi da request.get che iniziano con 'data_inizio' e
        # trasformo i value da stringhe a funzioni
        filtro_data = {k: eval(v) for k,v in self.request.GET.items() if k.startswith('data_inizio') and v.startswith('timezone.')}
        # creo un Q object
        q_objects = Q()
        # metto in OR i vari filtri
        for key, value in filtro_data.items():
            q_objects.add(Q(**{key: value}), Q.OR)

        # prende il valore per il prezzo e lo splitta in due, prima e dopo '-', inoltre
        # lo trasforma in float per poter effettuare un controllo
        try:
            filtro_prezzo = list(map(float, (self.request.GET.get('prezzo')).split('-')))
        except AttributeError:
            filtro_prezzo = [0, (Asta.objects.all().aggregate(Max('prezzo')))['prezzo__max']]
        except ValueError:
            filtro_prezzo = 'corrupted url, not float value'

        if all(isinstance(item, float) for item in filtro_prezzo):
            return Asta.objects.filter(q_objects,
                prezzo__range=(filtro_prezzo[0], filtro_prezzo[1])
            ).order_by('-data_inizio')
        else:
            return Asta.objects.filter(q_objects,).order_by('-data_inizio')

# two different behaviour based on the request (get or post)
def dettagli(request, asta_id):
    if request.method == 'GET':
        asta = get_object_or_404(Asta, pk=asta_id)
        return render(request, 'aste/dettagli.html', {'asta': asta})
    if request.method == 'POST':
        if request.user.is_authenticated():
            # and request.user.has_perm('Asta.can_bid')
            asta = get_object_or_404(Asta, pk=asta_id)
            u = get_object_or_404(User, pk=request.user.id)
            # controllo che l'asta sia in corso e che l'utente che rilancia non sia quello che l'ha creata
            if asta.getState() == 1 and asta.added_by != u:

                pun = Puntata()
                pun.asta = asta
                pun.utente = u
                pun.somma = asta.prezzo + 0.25
                pun.data_puntata = timezone.now()
                pun.save()

                asta.prezzo = pun.somma
                asta.save()
                return render(request, 'aste/dettagli.html', {'asta': asta})
            else:
                return HttpResponseServerError("Utente creatore dell'asta non può rilanciare")
        else:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

@login_required
def send_mail(request):
    if request.method == 'POST':
        asta = get_object_or_404(Asta, pk=request.POST.get("asta_id"))
        u = get_object_or_404(User, pk=request.user.id)
        if asta.getState() == 2:
            msg="L'asta " + str(asta.descrizione) + " inizerà il " + str(asta.data_inizio) + ". \nPronto a vincere?"
            email = EmailMessage('Promemoria asta', msg, to=[u.email])
            email.send(fail_silently=False)
            return HttpResponseRedirect('/aste')
        else:
            return HttpResponseServerError("Bad request")

@staff_member_required
def creaAsta(request):
    return HttpResponseRedirect('/admin/aste/asta/add/')

aste/templates/aste/dettagli.html
{% extends 'base.html' %}
{% block head %}
  <title>dettagli</title>

  <script type="text/javascript">
    var closingTime = new Date({{ asta.getClosingTime|date:"Y,n,j,G,i,s" }});
    // Subtract 1 from month bc js months starts from 0
    closingTime.setMonth(closingTime.getMonth() - 1);
    closingTime = closingTime.getTime();
    // Update the count down every 1 second
    var x = setInterval(function() {

      // Get todays date and time
      var now = new Date().getTime();
      // Find the distance between now an the closingTime date
      var distance = closingTime - now;
      // Time calculations for days, hours, minutes and seconds
      //var days = Math.floor(distance / (1000 * 60 * 60 * 24));
      //var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
      var seconds = Math.floor((distance % (1000 * 60)) / 1000);
      // Display the result in the element with id="timer"
      document.getElementById("timer").innerHTML = "Mancano: " + minutes + " minuti " + seconds + " secondi ";
    }, 1000);
  </script>

{% endblock %}
{% block body %}
  <center>
    <header>
      <h1> {{ asta.descrizione }} </h1>
    </header>

    <section>
      <p> <img src="{{ asta.foto.url }}" alt="Not found" height="300" width="300"> </p>

      {% if asta.getState == 0 %}
        <p> Scaduta il: {{ asta.data_inizio }} </p>
        <p> Prezzo di vendita: {{ asta.prezzo }} &euro;</p>
      {% elif asta.getState == 1 %}
        <p id="timer"></p>
        <p> Prezzo attuale: {{ asta.prezzo }} &euro;</p>

        <form method="post">
          {% csrf_token %}

          <input type="submit" value="Rialza">
        </form>

      {% elif asta.getState == 2 %}
        <p> Inizierà: {{ asta.data_inizio }} </p>
        <p> Prezzo di partenza: {{ asta.prezzo }} &euro; </p>
        <form action="{% url 'aste:send_mail' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="asta_id" value="{{ asta.id }}">
          <input type="submit" value="Invia promemoria">
        </form>
      {% endif %}
    </section>

    </br></br>
    <footer>
      <a href="{% url 'main_page' %}"> Home </a></br>
      <a href="{% url 'aste:indice' %}"> Torna alle aste </a></br>
    </footer>
  </center>
{% endblock %}

aste/templates/aste/indice.html
{% extends 'base.html' %}
{% load url_replace %}
{% block head %}
  <title>indice</title>
{% endblock %}
{% block body %}
  <header>
    <h3>Aste disponibili:</h3>
  </header>

  <section>
    {% if latest_auctions_list %}
        <ul>
        {% for auction in latest_auctions_list %}
            <li><a href="{% url 'aste:dettagli' auction.id %}"> {{ auction.descrizione }} </a></li>
        {% endfor %}
        </ul>
        {% comment %} pagination section {% endcomment %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?{% url_replace page=page_obj.previous_page_number %}">precedente</a>
                    {% endif %}

                    <span class="current">
                        Pagina {{ page_obj.number }} di {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?{% url_replace page=page_obj.next_page_number %}">successiva</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    {% else %}
        <p>Non sono disponibili aste.</p>
    {% endif %}

    </br>
    <h4>Filtra per:</h4>
    <form method="get">
      {% csrf_token %}
      <b>data:</b>
      <input type="checkbox" name="data_inizio__lt" value="timezone.now()">scadute</br>
      <span style="margin-left:3em"><input type="checkbox" name="data_inizio__date" value="timezone.localdate()">oggi</span></br>
      <span style="margin-left:3em"><input type="checkbox" name="data_inizio__gt" value="timezone.now()">prossimamente</span></br>
      </br>
      <b>prezzo:</b>&nbsp;&nbsp;
      <input type="radio" name="prezzo" value="0-inf"> qualsiasi</br>
      <span style="margin-left:5em"><input type="radio" name="prezzo" value="0-50"> &euro; 0 - &euro; 50</br>
      <span style="margin-left:5em"><input type="radio" name="prezzo" value="50-200"> &euro; 50 - &euro; 200</span></br>
      <span style="margin-left:5em"><input type="radio" name="prezzo" value="200-500"> &euro; 200 - &euro; 500</span></br>
      <span style="margin-left:5em"><input type="radio" name="prezzo" value="500-inf"> > &euro; 500</span></br>
      </br>
      <input type="submit" value="Filtra">

    </form>
  </section>

  </br></br>
  <footer>
    <a href="{% url 'aste:creaAsta' %}"> Crea una nuova asta </a></br>
    <a href="{% url 'main_page' %}"> Home </a>
  </footer>
{% endblock %}